### ISSUE TITLE
Integration with NeoVim

### ISSUE THREAD

**Issue by pratikgajjar** [nrempel/sleek#1]
Thank you for RIIR - was aware about such plugin in python but didn't want to go through env setup. This looks awesome 🙌  

Do you have any plans for integration with Mason / Nvim package for `.sql` files formatting ?

**Comment by nrempel** [comment]
Thanks for checking it out! I'm not familiar with Mason. Would adding Github releases with binaries available for download be sufficient?

**Comment by nrempel** [comment]
I think this issue is better suited for https://github.com/mason-org/mason-registry

It looks like it should be possible to create a package using a binary once those are available #2 or use cargo directly.

https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md#bin
https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md#cargo

I'm going to close this as out of scope but I'm happy to answer any questions.
